// <auto-generated />
using System;
using InventoryManagement.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251219182713_BdInventory")]
    partial class BdInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("InventoryManagement.Models.categoria", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombreCategoria")
                        .HasColumnType("TEXT");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("categoriaId");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("InventoryManagement.Models.cliente", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("RNCCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCliente")
                        .HasColumnType("TEXT");

                    b.HasKey("clienteId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("InventoryManagement.Models.compra", b =>
                {
                    b.Property<int>("compraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("TEXT");

                    b.Property<string>("almacenDestino")
                        .HasColumnType("TEXT");

                    b.Property<double>("costoEnvio")
                        .HasColumnType("REAL");

                    b.Property<double>("descuento")
                        .HasColumnType("REAL");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<double>("impuesto")
                        .HasColumnType("REAL");

                    b.Property<string>("lugarRecepcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("metodoPago")
                        .HasColumnType("TEXT");

                    b.Property<string>("motivoAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("proveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("regionCompra")
                        .HasColumnType("TEXT");

                    b.Property<double>("subTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("tipoEntrega")
                        .HasColumnType("TEXT");

                    b.Property<double>("total")
                        .HasColumnType("REAL");

                    b.Property<string>("transportista")
                        .HasColumnType("TEXT");

                    b.HasKey("compraId");

                    b.ToTable("compras");
                });

            modelBuilder.Entity("InventoryManagement.Models.detalleCompra", b =>
                {
                    b.Property<int>("detalleCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("calidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("certificaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("compraId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("costoUnitario")
                        .HasColumnType("REAL");

                    b.Property<double>("descuentoUnitario")
                        .HasColumnType("REAL");

                    b.Property<double>("impuestoUnitario")
                        .HasColumnType("REAL");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("totalLinea")
                        .HasColumnType("REAL");

                    b.Property<string>("unidadMedida")
                        .HasColumnType("TEXT");

                    b.HasKey("detalleCompraId");

                    b.ToTable("detalleCompras");
                });

            modelBuilder.Entity("InventoryManagement.Models.detalleVenta", b =>
                {
                    b.Property<int>("detalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("descuentoUnitario")
                        .HasColumnType("REAL");

                    b.Property<double>("impuestoUnitario")
                        .HasColumnType("REAL");

                    b.Property<double>("margenGanancia")
                        .HasColumnType("REAL");

                    b.Property<double>("precioUnitario")
                        .HasColumnType("REAL");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("promocionAplicada")
                        .HasColumnType("TEXT");

                    b.Property<double>("totalLinea")
                        .HasColumnType("REAL");

                    b.Property<string>("ubicacionAlmacen")
                        .HasColumnType("TEXT");

                    b.Property<string>("unidadMedida")
                        .HasColumnType("TEXT");

                    b.Property<int>("ventaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("detalleVentaId");

                    b.ToTable("detalleVentas");
                });

            modelBuilder.Entity("InventoryManagement.Models.entrada", b =>
                {
                    b.Property<int>("entradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadProducto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("catidadCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("entradaId");

                    b.ToTable("entradas");
                });

            modelBuilder.Entity("InventoryManagement.Models.producto", b =>
                {
                    b.Property<int>("productoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("advertencias")
                        .HasColumnType("TEXT");

                    b.Property<string>("alergenos")
                        .HasColumnType("TEXT");

                    b.Property<string>("azucares")
                        .HasColumnType("TEXT");

                    b.Property<int>("calorias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("carbohidratos")
                        .HasColumnType("TEXT");

                    b.Property<string>("codigoBarras")
                        .HasColumnType("TEXT");

                    b.Property<string>("colesterol")
                        .HasColumnType("TEXT");

                    b.Property<string>("distribución")
                        .HasColumnType("TEXT");

                    b.Property<string>("empaque")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaCaducidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaElaboracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("fibraDietetica")
                        .HasColumnType("TEXT");

                    b.Property<string>("grasasSaturadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("grasasTrans")
                        .HasColumnType("TEXT");

                    b.Property<double>("impuesto")
                        .HasColumnType("REAL");

                    b.Property<string>("ingredientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("instruccionesUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("libreDe")
                        .HasColumnType("TEXT");

                    b.Property<string>("lote")
                        .HasColumnType("TEXT");

                    b.Property<string>("marca")
                        .HasColumnType("TEXT");

                    b.Property<double>("margenGanancia")
                        .HasColumnType("REAL");

                    b.Property<string>("nivelAcidez")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("paisOrigen")
                        .HasColumnType("TEXT");

                    b.Property<int>("pesoVolumenNeto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("porcionesEnvase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("posicionTienda")
                        .HasColumnType("TEXT");

                    b.Property<double>("precioDescuento")
                        .HasColumnType("REAL");

                    b.Property<double>("precioKiloLitro")
                        .HasColumnType("REAL");

                    b.Property<double>("precioMayor")
                        .HasColumnType("REAL");

                    b.Property<double>("precioUnidad")
                        .HasColumnType("REAL");

                    b.Property<double>("precios")
                        .HasColumnType("REAL");

                    b.Property<string>("presentacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("proteinas")
                        .HasColumnType("TEXT");

                    b.Property<string>("sabor")
                        .HasColumnType("TEXT");

                    b.Property<string>("sodio")
                        .HasColumnType("TEXT");

                    b.Property<string>("tamanoPorcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("temperaturaConservacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("textura")
                        .HasColumnType("TEXT");

                    b.Property<string>("vidaUtil")
                        .HasColumnType("TEXT");

                    b.Property<string>("vitaminasMinerales")
                        .HasColumnType("TEXT");

                    b.HasKey("productoId");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("InventoryManagement.Models.proveedor", b =>
                {
                    b.Property<int>("proveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RNCProveedor")
                        .HasColumnType("TEXT");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("llegada")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("retirada")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("proveedorId");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("InventoryManagement.Models.salida", b =>
                {
                    b.Property<int>("salidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadProducto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("salidaId");

                    b.ToTable("salidas");
                });

            modelBuilder.Entity("InventoryManagement.Models.user", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("rol")
                        .HasColumnType("TEXT");

                    b.Property<string>("userName")
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("InventoryManagement.Models.venta", b =>
                {
                    b.Property<int>("ventaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("caja")
                        .HasColumnType("TEXT");

                    b.Property<string>("cajero")
                        .HasColumnType("TEXT");

                    b.Property<string>("canalVenta")
                        .HasColumnType("TEXT");

                    b.Property<double>("cashback")
                        .HasColumnType("REAL");

                    b.Property<int>("clienteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("descuento")
                        .HasColumnType("REAL");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<double>("gananciaBruta")
                        .HasColumnType("REAL");

                    b.Property<double>("impuesto")
                        .HasColumnType("REAL");

                    b.Property<string>("metodoPago")
                        .HasColumnType("TEXT");

                    b.Property<string>("moneda")
                        .HasColumnType("TEXT");

                    b.Property<string>("motivoAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroFactura")
                        .HasColumnType("TEXT");

                    b.Property<string>("origenCampaña")
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .HasColumnType("TEXT");

                    b.Property<string>("segmento")
                        .HasColumnType("TEXT");

                    b.Property<double>("subTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("tasaCambio")
                        .HasColumnType("REAL");

                    b.Property<double>("total")
                        .HasColumnType("REAL");

                    b.Property<string>("ubicacionAlmacen")
                        .HasColumnType("TEXT");

                    b.Property<string>("usuarioRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("vendedor")
                        .HasColumnType("TEXT");

                    b.HasKey("ventaId");

                    b.ToTable("ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
